var router = require('express').Router();

const { Checkout } = require('checkout-sdk-node');
const cko = new Checkout('sk_sbox_n2dvcqjweokrqm4q7hlfcfqtn4m');

router.post('/pay', async (req, res) => {
    // The token generated by Frames on the front end
    const myToken = req.body.token;

    const paymentResponse = await cko.payments.request({
        source: {
            token: myToken,
        },
        currency: 'GBP',
        processing_channel_id: 'pc_zs5fqhybzc2e3jmq3efvybybpq',
        amount: 2499,
        risk: {
            enabled: false,
        },
    });

    res.send(paymentResponse);
});

module.exports = router;
