// "checkout-sdk-node": "^2.1.1"

var router = require('express').Router();

const { Checkout } = require('checkout-sdk-node');
const cko = new Checkout('sk_sbox_XXX');

router.post('/pay', async (req, res) => {
    // The token generated by Frames on the front end
    const myToken = req.body.token;

    const paymentResponse = await cko.payments.request({
        source: {
            token: myToken,
        },
        amount: 2499,
        currency: 'GBP',
        processing_channel_id: 'pc_XXX',
        risk: {
            enabled: false,
        },
    });

    res.send(paymentResponse);
});

module.exports = router;
