name: Create Java Package
 
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'java/**'

jobs:
  create_java_package_and_push:
    name: Create Java package and push
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Zip Java files
        run: |
           zip -r ../java.zip java

      - name: Checkout packages branch
        uses: actions/checkout@v3
        with:
          ref: packages

      - name: Move zip Java file to workspace
        run: |
          mv ../java.zip .

      - name: Push zip Java file to packages branch
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-action@users.noreply.github.com"
          git add java.zip
          git commit -m "Added new Java package: '${{ github.event.pull_request.title }}'"
          git push
          
  